name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: CISE_Worksheet3/mern_week3
        run: npm install

      - name: Build the app
        working-directory: CISE_Worksheet3/mern_week3
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_SECRET }}
        run: npx vercel --token $VERCEL_TOKEN --prod --confirm